# -*- coding: utf-8 -*-
"""GRUPO_6_TAREA2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6DN29jGCMzOSY1uRSPbXIXPFNIrjO4r
"""

import pandas as pd

""" I. Copia el siguiente diccionario en una cédula de Colab. A partir de él, crea un dataframe
llamado nfo utilizando Pandas.
"""

data_ciudades = {
    "Ciudad": ["Lima", "Arequipa", "Trujillo", "Cusco", "Chiclayo", "Piura", "Iquitos", "Huancayo", "Tacna", "Pucallpa"],
    "Habitantes": [1047996, 100169, 92331, 428450, 305717, 484475, 441649, 385098, 294395, 283734],
    "Area_km2": [2672.28, 1545.77, 1487.7, 116.5, 279.89, 6217.26, 368.9, 109.19, 59.4, 483.44],
    "Altitud_m": [154, 2325, 34, 3399, 29, 29, 106, 3271, 562, 156],
    "Densidad_poblacion_por_km2": [3924, 64.8, 62.1, 3673, 1091.6, 77.9, 1196, 3528.6, 4966, 587.2]
}

nfo = pd.DataFrame(data_ciudades)
nfo

""" II. Realiza el mismo procedimiento con el siguiente diccionario. A partir de él, crea un
dataframe llamado nombres.


"""

data_ciudades_2 = {
    'Ciudad': ['Lima', 'Arequipa', 'Trujillo', 'Cusco', 'Chiclayo', 'Piura', 'Iquitos', 'Huancayo', 'Tacna', 'Pucallpa'],
    'Gentilicio': ['Limense', 'Arequipeño', 'Trujillano', 'Cusqueño', 'Chiclayano', 'Piurano', 'Iquiteño', 'Huancaíno', 'Tacneño', 'Pucallpino'],
    'Provincia': ['Lima', 'Arequipa', 'Trujillo', 'Cusco', 'Chiclayo', 'Piura', 'Maynas', 'Huancayo', 'Tacna', 'Coronel Portillo'],
    'Region': ['Lima', 'Arequipa', 'La Libertad', 'Cusco', 'Lambayeque', 'Piura', 'Loreto', 'Junín', 'Tacna', 'Ucayali']
}
nombres=pd.DataFrame(data_ciudades_2)
nombres

"""III. Con ambos dataframes, realiza un inner join. Guarda el resultado en un nuevo dataframe
llamado cuadro_1
"""

cuadro_1= pd.merge(nfo, nombres, on='Ciudad', how='inner')
cuadro_1

""" IV. Resume las estadísticas descriptivas del dataframe y responde ¿Cuál es la mínima
densidad poblacional? ¿A cuál ciudad corresponde? ¿Y la máxima?
"""

texto_1= ('''La minima densidad poblacional es de 62.1, correspondiente a Trujillo.
 La maxima densidad poblacional es de 4966, correspondiente a la ciudad de Tacna''')

print(texto_1)

import matplotlib.pyplot as plt

"""V. Realizar un gráfico de barras donde se vea la cantidad de habitantes en cada ciudad"""

fig, ax = plt.subplots(figsize=(10, 8))
ax.bar(cuadro_1['Ciudad'], height=cuadro_1['Habitantes'], color = "steelblue")
ax.set_title ("Numero de habitantes por ciudad en Perú")
ax.set_xlabel("Ciudad")
ax.set_ylabel("Habitantes")
ax.tick_params(axis="x", rotation=45)
plt.show()

""" VI. Realizar un gráfico de dispersión entre la altura y el número de habitantes en las
ciudades del dataframe.
"""

fig,ax = plt.subplots(figsize=(10, 6))
ax.scatter(cuadro_1["Altitud_m"], cuadro_1["Habitantes"], color = "green")
ax.set_title ("Relacion entre altitud y Numero de habitantes de las ciudades en Peru")
ax.set_xlabel("Altitud(m)")
ax.set_ylabel("Habitantes")
ax.grid(True, alpha=0.5)
plt.show()